// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWHfFR6uZBRryRY3ZkLXVn8_hyHEJjkg',
    appId: '1:32317141213:web:4fc843f2c0fa0a7d7b6b34',
    messagingSenderId: '32317141213',
    projectId: 'evently-40613',
    authDomain: 'evently-40613.firebaseapp.com',
    storageBucket: 'evently-40613.firebasestorage.app',
    measurementId: 'G-9FC47D97ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQlJFEY-SawIbGxYqWpxy2rgRcEl3zD7s',
    appId: '1:32317141213:android:b492f5b2cd164a187b6b34',
    messagingSenderId: '32317141213',
    projectId: 'evently-40613',
    storageBucket: 'evently-40613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_4p6qbyp32qn45Fv17ieQhYhZYYMnfw',
    appId: '1:32317141213:ios:4d5077ffc46c90c47b6b34',
    messagingSenderId: '32317141213',
    projectId: 'evently-40613',
    storageBucket: 'evently-40613.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_4p6qbyp32qn45Fv17ieQhYhZYYMnfw',
    appId: '1:32317141213:ios:4d5077ffc46c90c47b6b34',
    messagingSenderId: '32317141213',
    projectId: 'evently-40613',
    storageBucket: 'evently-40613.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpWHfFR6uZBRryRY3ZkLXVn8_hyHEJjkg',
    appId: '1:32317141213:web:8ffff7d92e09d8ce7b6b34',
    messagingSenderId: '32317141213',
    projectId: 'evently-40613',
    authDomain: 'evently-40613.firebaseapp.com',
    storageBucket: 'evently-40613.firebasestorage.app',
    measurementId: 'G-9D2P472FW7',
  );
}
